name: Build
on: [push, pull_request]

env:
  RUSTFLAGS: '--deny warnings'

jobs:
  build:
    name: Check and Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, nightly] # support for Rtic v2 requires nightly
        TARGET:
          - arm-unknown-linux-gnueabi # Raspberry Pi 1
          - armv7-unknown-linux-gnueabihf # Raspberry Pi 2, 3, etc
          # Bare metal
          - thumbv6m-none-eabi
          - thumbv7em-none-eabi
          - thumbv7em-none-eabihf
          - thumbv7m-none-eabi

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.TARGET }}

      - name: Add specific Rust targets for bare metal builds
        run: rustup target add ${{ matrix.TARGET }}

      - name: Checkout CI scripts
        uses: actions/checkout@v4
        with:
          repository: 'eldruin/rust-driver-ci-scripts'
          ref: 'master'
          path: 'ci'

      - run: ./ci/patch-no-std.sh
        if: ${{ ! contains(matrix.TARGET, 'x86_64') }}

      - run: cargo check --target=${{ matrix.TARGET }} # fast fail early

      - run: cargo build --target=${{ matrix.TARGET }}

  checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu,thumbv7em-none-eabihf
          components: rustfmt

      - run: cargo doc
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.75.0
          targets: x86_64-unknown-linux-gnu,thumbv7em-none-eabihf
          components: clippy

      - run: cargo clippy --all-targets
